apiVersion: apps/v1
kind: Deployment
metadata:
  name: iptables-agent
  namespace: iptable
  labels:
    app: iptables-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iptables-agent
  template:
    metadata:
      labels:
        app: iptables-agent
    spec:
      containers:
        - name: iptables-agent
          image: http://harbor.cdl.local/myproject/server:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true         # requerido para manipular iptables
          ports:
            - containerPort: 8000
              name: http
      restartPolicy: Always
      imagePullSecrets:
        - name: harbor-registry-secret   # Secreto con credenciales de Harbor
