apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kafka-iptable
  namespace: argo-events
spec:
  kafka:
    iptable-source:
      url: 10.10.12.159:9092
      topic: iptable
      consumerGroup:
        groupId: iptables-agent
      partition: "0"
      jsonBody: true  # o false, según tu formato
