apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kafka-iptable
  namespace: argo-events
spec:
  kafka:
    iptable-source:
      #  Solo host:puerto, SIN prefijo
      url: 10.10.12.159:9092

      topic: iptable

      consumerGroup:
        groupName: iptables-agent
        rebalanceStrategy: range

      # Si tienes una sola partici칩n, no a침adas 'partition'
      # partition: "0"

      # Versi칩n de protocolo m치s alta soportada por Sarama
      version: "3.0.0"

      jsonBody: true
