apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kafka-iptable
  namespace: argo-events
spec:
  kafka:
    iptable-source:
      url: 10.10.12.159:9092
      topic: iptable
      consumerGroup:
        groupName: "iptables-agent"     # ✅ clave y valor
      jsonBody: true
      # version: "3.0.0"  ← puedes quitarla, Sarama autodetecta
