apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kafka-iptable
  namespace: argo-events
spec:
  kafka:
    iptable-source:
      url: 10.10.12.159:9092        # sin “PLAINTEXT://”
      topic: iptable
      consumerGroup:
        groupId: iptables-agent
      version: "3.0.0"              # o quítalo, Sarama autodetecta
      jsonBody: true
