apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-iptable
  namespace: argo-events
spec:
  dependencies:
    - name: kafka-iptable-dep
      eventSourceName: kafka-iptable
      eventName: iptable-source
  triggers:
    - template:
        name: call-iptables-service
        http:
          url: http://iptables-agent.iptable.svc.cluster.local:8000/iptables-rule
          method: POST
          timeout: 10000
          payload:
            - src:
                dependencyName: kafka-iptable-dep
                dataKey: body.rule   # <– extrae solo el campo `rule` del mensaje Kafka
              dest: rule             # <– lo sitúa directamente como clave raíz en el JSON
      retryStrategy:
        steps: 3
        duration: 5s
        factor: 2
