apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-iptable
  namespace: argo-events
spec:
  dependencies:
    - name: kafka-iptable-dep
      eventSourceName: kafka-iptable
      eventName: iptable-source        # debe coincidir con la clave del EventSource
  triggers:
    - template:
        name: call-iptables-service
        http:
          url: http://iptables-agent.iptable.svc.cluster.local:8000/iptables-rule
          method: POST
          timeout: 10000
          payload:
            - src:
                dependencyName: kafka-iptable-dep
                dataKey: body          # cuerpo completo del mensaje Kafka
              dest: spec.rule          # se convertir치 en {"rule": "<mensaje>"}
          # Argo Events a침adir치 autom치ticamente header Content-Type: application/json
      retryStrategy:
        steps: 3
        duration: 5s
        factor: 2
