apiVersion: v1
kind: Service
metadata:
  name: iptables-agent
  namespace: iptable
spec:
  selector:
    app: iptables-agent
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
